// document.write("<center><h1><u>Curriculum Vitae</u></h1></center>");
document.write("<h1><u>Curriculum Vitae</u></h1>");
document.write("<h1>Yashesh Mehta</h1>");
// document.write("<br>");
document.write("Maninagar");
document.write("<br>");
document.write("Ahmedabad-50");
document.write("<br>");
document.write("9876543210");
document.write("<hr>");
document.write("<h1 style='background-color : grey'>Career Objective</h1>")//.style.backgroundColor = "grey";
document.write("<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quasi distinctio id sed eius dolorem iste blandit <br> iis, dicta repellat impedit sit, incidunt eligendi excepturi. Nemo molestiae voluptates atque, aut <br>unde vel?Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat, quibusdam.</p>");
document.write("<h1 style='background-color : grey'>Academic Qualification</h1>");
document.write("<p>&#11162;10th passed from G.S.E.B.</p>");
document.write("<p>&#11162;12th passed from G.S.E.B.</p>");
document.write("<p>&#11162;Pursuing BE  in Computer Engineering from V.G.E.C.</p>");
document.write("<h1 style='background-color : grey'>Other Qualification</h1>");
document.write("<p>&#11162;Basic kowledge of Web Development.</p>");
// document.write("<h1>Experience</h1>");
// document.write("<p>&#11162;</p>");
// document.write("<p>&#11162;</p>");
document.write("<h1 style='background-color : grey'>Personal Skill</h1>");
document.write("<p>&#11162;Team Sprit</p>");
document.write("<p>&#11162;Honesty</p>");
document.write("<p>&#11162;Focused towards work</p>");
document.write("<h1 style='background-color : grey'>Personal Profile</h1>");
document.write("<p>&#11162;<b>Father's Name</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jigar Mehta</p>");
document.write("<p>&#11162;<b>Date of Birth</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;11/09/05</p>");
document.write("<p>&#11162;<b>Languages Known</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;English & Hindi</p>");
document.write("<h1 style='background-color : grey'>Declaration</h1>");
document.write("Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus enim, iste deserunt doloremque quo aperiam.");
document.write("<br>");
document.write("Date: 20/05/2024");
document.write("<br>");
document.write("Place: Ahmedabad");